# Private Email Configuration Settings (here for Gmail account as sender mail)
smtp_server = 'smtp.gmail.com'                                                      # SMTP server address
smtp_port = 587                                                                     # SMTP port (587 for TLS)
smtp_password = 'ctij wnin frxl ggup'                                               # App Password that is generated by Google for your gmail address
sender_email = 'maexemc@gmail.com'                                                  # List of your sender email address
recipient_emails = ['maexemc@gmail.com']                                            # List of all recipient email addresses

def get_email_subject(class_name, time, manual):

    if manual:
        class_name = class_name.replace("-", ", ")                                  # Convert names like 'dog-fox' to 'dog, fox'
        if class_name == "":                                                        # If during manual recording no objects were detected convert '' to 'no objects' (change this in accordance to your specific needs)
            class_name = "no objects"
        return subject_for_manual_detection(class_name, time)              
    else:
        return subject_for_automated_detection(class_name, time)              
        

def get_email_body(class_name, time, manual):
    
    if manual:
        class_name = class_name.replace("-", ", ")
        if class_name == "":
            class_name = "no objects"
        return text_for_manual_detection(class_name, time)              
    else:
        return text_for_automated_detection(class_name, time)  


# Customizable Email Content
#######################################################################################
# MODIFY THE CONTENT BELOW TO SUIT YOUR NEEDS

def subject_for_manual_detection(class_name, time):

    return f"Manual Object Detection of '{class_name}' at time {time}"


def subject_for_automated_detection(class_name, time):

    return f"Automatic Object Detection of '{class_name}' at time {time}"


def text_for_manual_detection(class_name, time):

    return f"""Dear User,

The following objects have been detected during your manual recording at time {time}: 
{class_name}

Kind Regards,
"""


def text_for_automated_detection(class_name, time):

    return f"""Dear User,

The following object has been automatically detected at time {time}: 
{class_name}

Kind Regards,
"""

#######################################################################################
# MODIFY THE CONTENT ABOVE TO SUIT YOUR NEEDS
